version: '3.8'

services:
  mfe_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../../src:/app/src
    environment:
      PYTHONPATH: /app/src
      PYTHONUNBUFFERED: '1'
      QT_QPA_PLATFORM: offscreen
    ports:
      - "8000:8000"
    networks:
      - mfe_network

networks:
  mfe_network:
    driver: bridge

volumes:
  src: