name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.12' ]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest==7.4.3 pytest-asyncio==0.21.1 pytest-cov==4.1.0
        pip install numpy==1.26.3 scipy==1.11.4 pandas==2.1.4 statsmodels==0.14.1
        pip install numba==0.59.0 PyQt6==6.6.1
    - name: Run tests with coverage
      run: pytest --cov=mfe --cov-report=xml --cov-report=term-missing --cov-fail-under=90

  type-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install mypy
      run: pip install mypy==1.7.0
    - name: Run type checking
      run: mypy mfe --config-file mypy.ini

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install flake8
      run: pip install flake8==6.1.0
    - name: Run linting
      run: flake8 mfe --config flake8.ini